import { cn } from "@/lib/classnames";
import { font } from "@/lib/font";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body className={cn(font.variable, "bg-slate-100 font-mono")}>{children}</body>
    </html>
  );
}
